apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: maarten-3scale
  labels:
    app: service-b
    app.kubernetes.io/component: service-b
    app.kubernetes.io/instance: service-b
    app.kubernetes.io/name: service-b
    app.kubernetes.io/part-of: service-b
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: service-b
    deployment: service-b
  type: ClusterIP