apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: maarten-3scale
  name: 'service-c'
  annotations: {}
  labels:
    app: service-c

    app.kubernetes.io/component: service-c
    app.kubernetes.io/instance: service-c
    app.kubernetes.io/name: service-c
    app.kubernetes.io/part-of: service-c
    app.openshift.io/runtime-namespace: maarten-3scale
spec:
  selector:
    matchLabels:
      app: service-c
  replicas: 2
  template:
    metadata:
      labels:
        app: service-c
        version: v1
        app.kubernetes.io/component: service-c
        app.kubernetes.io/name: service-c
        deployment: service-c
      annotations:
        sidecar.istio.io/inject: "true"

        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/service-c/q/metrics"
    spec:
      containers:
        - name: container
          image: >-
            quay.io/appdev_playground/service-mesh-basic-example:service-c-0.0.22
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
